name: KTX-Software Linux CI

on:
  push
    branches: [ main ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'
    paths-ignore:
      - '**.md'
      - '.github/workflows/*.yml'
      - '!**/linux.yml'
  workflow_dispatch:

jobs:
  build-linux:
    strategy:
      matrix:
        include:
          - name: Default
            os: ubuntu-latest
            compiler: gcc
            generator: Ninja
            options: { config: Debug, py: ON, tools: ON, loadtests: OpenGL+Vulkan, sse: ON, opencl: OFF }
          - name: Clang
            os: ubuntu-latest
            compiler: clang
            generator: Ninja
            options: { config: Release, py: ON, tools: ON, loadtests: OpenGL+Vulkan, sse: ON, opencl: OFF }
          - name: OpenCL only
            os: ubuntu-22.04
            compiler: gcc
            generator: Ninja
            options: { config: Release, py: OFF, tools: OFF, loadtests: OFF, sse: OFF, opencl: ON }

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    env:
      BUILD_DIR: build
      CMAKE_GEN: ${{ matrix.generator }}
      CONFIGURATION: ${{ matrix.options.config }}
      FEATURE_PY: ${{ matrix.options.py }}
      FEATURE_TOOLS: ${{ matrix.options.tools }}
      FEATURE_LOADTESTS: ${{ matrix.options.loadtests }}
      SUPPORT_SSE: ${{ matrix.options.sse }}
      SUPPORT_OPENCL: ${{ matrix.options.opencl }}
      VCPKG_BINARY_SOURCES: clear
      PYTHON_DIST_DIR: interface/python_binding/dist

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set compiler
        run: |
          if [ "${{ matrix.compiler }}" = "gcc" ]; then
            echo "CC=gcc" >> $GITHUB_ENV
            echo "CXX=g++" >> $GITHUB_ENV
          elif [ "${{ matrix.compiler }}" = "clang" ]; then
            echo "CC=clang" >> $GITHUB_ENV
            echo "CXX=clang++" >> $GITHUB_ENV
          fi

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build git mono-complete libltdl-dev

      - name: Setup Python
        if: matrix.options.py == 'ON'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        if: matrix.options.py == 'ON'
        run: |
          pip install virtualenv

      - name: Configure Git for smudge scripts
        run: |
          ./install-gitconfig.sh
          ./scripts/smudge_date.sh

      - name: Build
        run: |
          ./scripts/install_linux.sh
          ./scripts/build_linux.sh

      - name: Upload Python artifact
        if: matrix.options.py == 'ON'
        uses: actions/upload-artifact@v4
        with:
          name: pyktx-${{ matrix.name }}
          path: ${{ env.BUILD_DIR }}/${{ env.PYTHON_DIST_DIR }}

